version: '3'
services:
  rabbitmq_broker:
      build: .
      volumes:
        - .:/opt/script_print_rabbitmq
      environment:
          RABBITMQ_USER : guest
          RABBITMQ_PASSWORD : guest
          RABBITMQ_HOST : 10.0.0.5
          RABBITMQ_PORT : 5672
          RABBITMQ_PATH : 2f
          RABBITMQ_EXCHANGE_NAME : exchange_name
          RABBITMQ_DELIVERY_MODE : 2
          FILELOG : /var/log/print_rabbitmq.log
          LOG_LEVEL : INFO
          QUEUE_NAME : colissimo
          PRINTER_NAME : HP_Color_LaserJet_MFP_M476nw
          QUEUE_CONFIGURATION : raspberry
      restart: always
      working_dir: /opt/script_print_rabbitmq
      command: ./print_rabbitmq.py
      #command: /etc/init.d/print_rabbitmq restart
      links:
        - cups

  cups:
      image: thbe/cups
      volumes:
        - ./config/cupsd.conf:/etc/cups/cupsd.conf:z
      ports:
        - 631:631
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.printer.rule=Host(`printer.local`)"
        - "traefik.http.routers.printer.service=printer"
        - "traefik.http.services.printer.loadbalancer.server.port=631"

networks:
  default:
      driver: bridge

