version: '3'
services:
  rabbitmq_broker:
      build: .
      volumes:
        - .:/opt/script_print_rabbitmq
      env_file:
        - /opt/file_env/file.env
      environment:
          UDEV : 1
          RABBITMQ_USER : guest
          RABBITMQ_PASSWORD : guest
          RABBITMQ_HOST : dev_rabbitmq
          RABBITMQ_PORT : 5672
          RABBITMQ_PATH : 2f
          RABBITMQ_EXCHANGE_NAME : exchange_name
          RABBITMQ_DELIVERY_MODE : 2
          FILELOG : /var/log/print_rabbitmq.log
          LOG_LEVEL : INFO
          QUEUE_NAMES : colissimo,manual,chronopost
          QUEUE_CONFIGURATION : config_raspberry
          HTTPS : 0
          #RASPBERRY_NAME : raspberry_name
      restart: always
      working_dir: /opt/script_print_rabbitmq
      command: ./print_rabbitmq.py
      privileged: true
      devices:
          - /dev:/dev
      links:
        - cups

  cups:
      image: thbe/cups
      volumes:
        - ./config/cupsd.conf:/etc/cups/cupsd.conf:z
        - ../infomations_printer_rpi:/opt/scripts
      env_file:
        - /opt/file_env/file.env
      ports:
        - 631:631
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.printer.rule=Host(`printer.local`)"
        - "traefik.http.routers.printer.service=printer"
        - "traefik.http.services.printer.loadbalancer.server.port=631"

networks:
  default:
      driver: bridge

