FROM python:3.7-buster

RUN apt-get update && apt-get -y install \
whois \
wget \
lynx \
cups-filters \
foomatic-db-compressed-ppds \
printer-driver-all \
openprinting-ppds \
build-essential \
libssl-dev libffi-dev \
libxml2-dev \
libxslt1-dev \
zlib1g-dev \
libcups2-dev \
locales \
sudo \
whois \
cups \
foomatic-db-compressed-ppds \
openprinting-ppds \
gutenprint-locales \
python-nmap \
cups-client \
vim

#COPY ./print_rabbitmq_module/print_rabbitmq.py /opt/script_print_rabbitmq/

COPY ./print_rabbitmq_module/requirements.txt /tmp/
RUN pip3 install -r /tmp/requirements.txt

COPY ./print_rabbitmq_module/broker_rabbit /tmp/broker_rabbit
RUN pip3 install /tmp/broker_rabbit


COPY ./print_rabbitmq_module/print_rabbitmq.py /opt/script_print_rabbitmq/

EXPOSE 631
EXPOSE 5672

WORKDIR /opt/script_print_rabbitmq/
CMD [ "/opt/script_print_rabbitmq/print_rabbitmq.py" ]

