version: '3'
services:
  rabbitmq_broker:
      build: .
      volumes:
        - .:/opt/script_print_rabbitmq
      environment:
          RABBITMQ_USER : guest
          RABBITMQ_PASSWORD : guest
          RABBITMQ_HOST : 10.0.0.4
          RABBITMQ_PORT : 5672
          RABBITMQ_PATH : 2f
          RABBITMQ_EXCHANGE_NAME : exchange_name
          RABBITMQ_DELIVERY_MODE : 2
          FILELOG : /var/log/print_rabbitmq.log
          LOG_LEVEL : INFO
          QUEUE_NAME : colissimo
          PRINTER_NAME : HP_Color_LaserJet_MFP_M476nw
      restart: always
      working_dir: /opt/script_print_rabbitmq
      command: ./print_rabbitmq.py
      #command: /etc/init.d/print_rabbitmq restart

networks:
  default:
    external:
      name: dev_teclib

