version: '3'
services:
  rabbitmq_broker:
      build: .
      volumes:
        - .:/opt/script_print_rabbitmq
      environment:
          UDEV : 1
          RABBITMQ_USER : admin
          RABBITMQ_PASSWORD : IWmnh7hqWczlk
          RABBITMQ_HOST : service.rabbitmq.recette-erp12.interne.inkia.fr
          RABBITMQ_PORT : 5672
          RABBITMQ_PATH : 2F
          RABBITMQ_EXCHANGE_NAME : exchange_name
          RABBITMQ_DELIVERY_MODE : 2
          FILELOG : /var/log/print_rabbitmq.log
          LOG_LEVEL : INFO
          QUEUE_NAMES : colissimo,manual,chronopost
          QUEUE_CONFIGURATION : config_raspberry
          HTTPS : 1
      restart: always
      privileged: true
      devices:
          - /dev:/dev
      network_mode : host

  cups:
      image: lemariva/rpi-cups
      network_mode : host
      volumes:
        - ./config/cupsd.conf:/etc/cups/cupsd.conf:z
      ports:
        - 631:631
      restart: always


