image: docker:stable
services:
 - name: docker:dind
   command: ["--experimental"]

variables:
  DOCKER_DRIVER: overlay2


before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin

stages:
  - Build config
  - Build printer


docker build config:
  stage: Build config
  only:
    - v2
  script:
#    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:config ./config
#    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:config
    - mkdir -p /etc/docker && echo '{"experimental": true}' > /etc/docker/daemon.json
    - mkdir -p ~/.docker/cli-plugins
    - wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker buildx  --platform "linux/arm/v7" -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:config_arm32v7 ./config
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:config_arm32v7

docker build printer:
  stage: Build printer
  only:
    - v2
  script:
#    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:printer ./printer
#    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:printer
    - docker buildx  --platform "linux/arm/v7" -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:printer_arm32v7 ./printer
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:printer_arm32v7


