version: '3.6'
services:
  odoo-box-config:
    container_name: odoo-box-config
    hostname: odoo-box-config
    image: registry.teclib-erp.com/teclib/odoo-box:config
    ports:
      - 8090:5000
    privileged: true
    restart: always
    volumes:
      - /var/run.docker.sock:/var/run/docker.sock
      - ~/.odoo-box.env:/opt/env.dev
    env_file:
        - ~/.odoo-box.env
    environment:
      UDEV : 1
      PATH_ENV_FILE : /opt/env.dev
      FLASK_DEBUG: 1
      FLASK_ENV: development
      CUPS_HOST: cups
      CUPS_USER: print
      CUPS_PASSWORD: print
    devices:
      - /dev:/dev
    external_links:
      - odoo-box-cups:cups

  odoo-box-printer:
    container_name: odoo-box-printer
    hostname: odoo-box-printer
    image: registry.teclib-erp.com/teclib/odoo-box:printer
    privileged: true
    restart: always
    volumes:
      - /tmp/print:/tmp/printed
    env_file:
        - ~/.odoo-box.env
    environment:
        UDEV : 1
        LOG_LEVEL : DEBUG
        CUPS_HOST: cups
        CUPS_USER: print
        CUPS_PASSWORD: print
    devices:
      - /dev:/dev
    external_links:
      - odoo-box-cups:cups

  odoo-box-cups:
    container_name: odoo-box-cups
    hostname: odoo-box-cups
    image: registry.teclib-erp.com/teclib/odoo-box:cups_arm7
    privileged: true
    ports:
      - 8091:631
    volumes:
      - /var/run/dbus:/var/run/dbus # usb
      - odoo_box_cups_data_dev:/etc/cups/ # for save regitered printers
      - /tmp/print:/tmp/printed # share pdf to print
    devices:
        - /dev:/dev
    restart: always

volumes:
  odoo_box_cups_data_dev:

networks:
  default:
      driver: bridge
