version: '3.6'
services:
  odoo-box-config:
    container_name: odoo-box-config
    build: .
    ports:
      - 8090:5000
    privileged: true
    restart: always
    volumes:
      - /var/run.docker.sock:/var/run/docker.sock
      - ~/.odoo-box.env:/opt/env.dev
      - ./app:/app
    env_file:
        - ~/.odoo-box.env
    environment:
      UDEV : 1
      PATH_ENV_FILE : /opt/env.dev
      FLASK_DEBUG: 1
      FLASK_ENV: development
      CUPS_HOST: cups
      CUPS_USER: print
      CUPS_PASSWORD: print
      CUPS_PORT: 8091
    devices:
      - /dev:/dev
    external_links:
      - odoo-box-cups:cups

networks:
  default:
      driver: bridge
