#cloud-config

hostname: inkia_printer
manage_etc_hosts: true
apt_preserve_sources_list: true

users:
  - name: inkia
    gecos: "Inkia Printer"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    plain_text_passwd: inkia
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

  - name: pi
    gecos: "Raspberry Pi"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    plain_text_passwd: raspberry
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

  - name: pirate
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

package_update: false
#package_upgrade: true
#package_reboot_if_required: true


timezone: "Europe/Paris"

write_files:
  - content: |
      {
          "auths": {
              "gitlab.teclib-erp.com": {
                  "auth": "bXBlcnJvY2hlYXU6TXBlMDIwOUAk"
              },
              "https://index.docker.io/v1/": {
                  "auth": "bXBlcnJvY2hlYXU6SHlzdGVyaWEx"
              },
              "registry.teclib-erp.com": {
                  "auth": "bXBlcnJvY2hlYXU6TXBlMDIwOUAk"
              }
          },
          "HttpHeaders": {
              "User-Agent": "Docker-Client/19.03.5 (linux)"
          }
      }
    path: "/root/.docker/config.json"
    owner: "root:root"
    permissions: "0700"

  - content: |
              version: '3'
              services:
                rabbitmq_broker:
                    image: registry.teclib-erp.com/teclib/odoo-box:arm7
                    environment:
                        UDEV : 1
                        FILELOG : /var/log/print_rabbitmq.log
                        HTTPS : 1
                        LOG_LEVEL : INFO
                    env_file:
                      - /opt/file_env/file.env
                    restart: always
                    privileged: true
                    volumes:
                      - /opt/file_env/:/opt/file_env/
                    devices:
                      - /dev:/dev
                    network_mode : host

                cups:
                    image: lemariva/rpi-cups
                    network_mode : host
                    privileged: true
                    volumes:
                      - ./config/cupsd.conf:/etc/cups/cupsd.conf:z
                    ports:
                      - 631:631
                    restart: always



    path: "/home/pi/docker-compose-print_rabbitmq.yml"
    owner: "root:root"

  - content: |
              version: '3'
              services:
                website:
                  container_name: raspberry-flask-website
                  image: registry.teclib-erp.com/teclib/odoo-box:flask_rpi_arm7
                  ports:
                    - 8050:5000
                  labels:
                    - "traefik.enable=true"
                    - "traefik.http.routers.site_web.rule=Host(`website.local`)"
                    - "traefik.http.routers.site_web.service=site_web"
                    - "traefik.http.services.site_web.loadbalancer.server.port=5000"
                  privileged: true
                  volumes:
                    - /opt/file_env/:/opt/file_env/:z
                  environment:
                    UDEV : 1
                    MAC_ADDRESS: 6e:0c:2e:7c:60:bd
                    PATH_ENV_FILE : /opt/file_env/
                  env_file:
                    - /opt/file_env/file.env
                  devices:
                    - /dev:/dev
              networks:
                default:
                    driver: bridge


    path: "/home/pi/docker-compose-flask_rpi.yml"
    owner: "root:root"


  - content: |
      #! /bin/sh
      ### BEGIN INIT INFO
      # Provides:          pull_teclib_docker
      # Required-Start:    docker
      # Required-Stop:     cloud-init
      # Default-Start:     2 3 4 5
      # Default-Stop:      0 1 6
      # Short-Description: Pull Teclib docker images
      # Description:       This pull Teclib docker images
      #                    /root/.docker/config.json must be set.
      ### END INIT INFO

      /home/pi/init_hypriot_docker.sh
      docker login registry.teclib-erp.com
      docker pull registry.teclib-erp.com/teclib/odoo-box:flask_rpi_arm7
      docker pull registry.teclib-erp.com/teclib/odoo-box:arm7
      docker pull lemariva/rpi-cups

    path: "/etc/init.d/pull_teclib_docker"
    owner: "root:root"
    permissions: "0755"


  - content: |
      #! /bin/sh
      ### BEGIN INIT INFO
      # Provides:          run_teclib_docker
      # Required-Start:    docker
      # Required-Stop:     cloud-init pull_teclib_docker
      # Default-Start:     2 3 4 5
      # Default-Stop:      0 1 6
      # Short-Description: Run Teclib docker images
      # Description:       This run Teclib docker images
      #                    /root/.docker/config.json must be set.
      ### END INIT INFO

      docker-compose -f /home/pi/docker-compose-flask_rpi.yml up -d
      docker-compose -f /home/pi/docker-compose-print_rabbitmq.yml up -d

    path: "/etc/init.d/run_teclib_docker"
    owner: "root:root"
    permissions: "0755"


  - content: |
      #! /bin/sh
      ### BEGIN INIT INFO
      # Provides:          run_portainer
      # Required-Start:    docker
      # Required-Stop:     cloud-init
      # Default-Start:     2 3 4 5
      # Default-Stop:      0 1 6
      # Short-Description: Run portainer image
      # Description:       This run portainer.
      #                    Docker manager
      ### END INIT INFO
      docker login
      docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock hypriot/rpi-portainer

    path: "/etc/init.d/run_portainer"
    owner: "root:root"
    permissions: "0755"


  - content: |
      RASPBERRY_NAME=inkiaprinter
      CUPS_PASSWORD=password
      CUPS_LOGIN=root
      QUEUE_NAMES=colissimo,manual,chronopost
      QUEUE_CONFIGURATION=config_raspberry
      RABBITMQ_USER=admin
      RABBITMQ_PASSWORD=IWmnh7hqWczlk
      RABBITMQ_HOST=service.rabbitmq.recette-erp12.interne.inkia.fr
      RABBITMQ_PORT=5672
      RABBITMQ_PATH=2F
      RABBITMQ_EXCHANGE_NAME=exchange_name
      RABBITMQ_DELIVERY_MODE=2
      RABBITMQ_HTTPS=1
      PRINTER_NAME=printer
      FILELOG=/var/log/print_rabbitmq.log
      LOG_LEVEL=INFO

    path: "/opt/file_env/default.env"
    owner: "root:root"
    permissions: "0755"



# These commands will be ran once on first boot only
#  - [mkdir, "-p", "/opt/file_env" ]
#  - [chmod, "-R", "777", "/opt/file_env" ]
#  - [echo, "'#! /bin/sh'", ">", "/opt/file_env/file.env" ]
runcmd:
  - [mkdir, "-p", "/home/pi" ]
  - [mkdir, "-p", "/home/pi/teclib" ]
  - [mkdir, "-p", "/opt/file_env" ]
  - [chmod, "-R", "777", "/opt/file_env" ]
  - [cp, "-f", "/opt/file_env/default.env", "/opt/file_env/file.env" ]
  - apt-get install -y policykit-1
#  - update-rc.d pull_teclib_docker defaults
#  - update-rc.d run_teclib_docker defaults
#  - update-rc.d run_portainer defaults
#  - service docker status > /home/pirate/docker_status_after_pull.log
#  - service pull_teclib_docker status > /home/pirate/pull_teclib_docker_status_after_pull.log
#  - service run_portainer status > /home/pirate/portainer_status_after_pull.log


power_state:
  delay: "now"
  mode: reboot
  message: Rebbot to finish install...
  condition: True
