version: '3'
services:
  website:
    container_name: raspberry-flask-website
    build: .
    ports:
      - 8050:5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site_web.rule=Host(`website.local`)"
      - "traefik.http.routers.site_web.service=site_web"
      - "traefik.http.services.site_web.loadbalancer.server.port=5000"
    privileged: true
    volumes:
      - /opt/file_env/:/opt/file_env/
    environment:
      UDEV : 1
      MAC_ADDRESS: 6e:0c:2e:7c:60:bd
      PATH_ENV_FILE : /opt/file_env/
    env_file:
      - /opt/file_env/file.env
    devices:
      - /dev:/dev
networks:
  default:
      driver: bridge
