FROM python:3.7-buster

RUN apt-get update && apt-get -y install \
whois \
wget \
lynx \
build-essential \
libssl-dev libffi-dev \
libxml2-dev \
libxslt1-dev \
zlib1g-dev \
libcups2-dev \
locales \
sudo \
whois \
cups \
printer-driver-all \
foomatic-db-compressed-ppds \
openprinting-ppds \
gutenprint-locales \
usbutils \
nmap

COPY ./flask_rpi/requirements.txt /opt/flask_rpi/requirements.txt

WORKDIR /opt/flask_rpi

RUN pip3 install -r requirements.txt

COPY ./flask_rpi /opt/flask_rpi

EXPOSE 5000
EXPOSE 8050
EXPOSE 80

ENTRYPOINT ["python3"]
CMD ["./app/run.py"]